# Generated by Django 4.0.4 on 2022-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('planning_time', models.TimeField()),
                ('self_estimated_time', models.TimeField()),
                ('real_time_spent', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('risk', models.CharField(blank=True, max_length=64)),
                ('estimated_time_by_calc', models.TimeField(blank=True)),
            ],
        ),
    ]
