# Generated by Django 4.0.4 on 2022-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_create_task_db_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_time_by_calc',
        ),
    ]
