# Generated by Django 4.0.4 on 2022-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_estimate_time_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_time_spent',
            field=models.TimeField(blank=True),
        ),
    ]
