# Generated by Django 4.0.4 on 2022-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_make_real_time_spent_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_time_spent',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
