# Generated by Django 3.2.16 on 2023-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('planning_time', models.TimeField()),
                ('self_estimated_time', models.TimeField()),
                ('real_time_spent', models.TimeField()),
                ('complexity_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6, null=True)),
                ('risk_of_exceeding_time', models.CharField(choices=[('NotRisky', 'Notrisky'), ('Ok', 'Ok'), ('Risky', 'Risky'), ('VeryRisky', 'Veryrisky')], max_length=10, null=True)),
                ('correctness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estimated_time_by_cals', models.TimeField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
