# Generated by Django 3.2.16 on 2023-01-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esttracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_time_by_cals',
            new_name='estimated_time_by_calc',
        ),
    ]
