# Generated by Django 3.2.16 on 2023-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esttracker', '0002_rename_estimated_time_by_cals_task_estimated_time_by_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complexity_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_of_exceeding_time',
            field=models.CharField(blank=True, choices=[('NotRisky', 'Notrisky'), ('Ok', 'Ok'), ('Risky', 'Risky'), ('VeryRisky', 'Veryrisky')], max_length=10, null=True),
        ),
    ]
