# Generated by Django 3.2.16 on 2023-02-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esttracker', '0005_alter_task_estimated_time_by_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correctness',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
