# Generated by Django 3.2.16 on 2023-02-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esttracker', '0006_alter_task_correctness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_time_spent',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_of_exceeding_time',
            field=models.CharField(blank=True, choices=[('Not risky', 'Not risky'), ('OK', 'OK'), ('Risky', 'Risky'), ('Very risky', 'Very risky')], max_length=10, null=True),
        ),
    ]
