# Generated by Django 3.1.7 on 2021-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('planning', models.CharField(max_length=100, null=True)),
                ('estimate', models.CharField(max_length=100, null=True)),
                ('realtime', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
