# Generated by Django 3.1.7 on 2021-02-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='level',
            field=models.CharField(choices=[('-', '-'), ('Easy', 'easy'), ('Difficult', 'difficult')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='risk',
            field=models.CharField(choices=[('_', '_'), ('OK', 'OK')], max_length=100, null=True),
        ),
    ]
