# Generated by Django 3.1.7 on 2021-02-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210227_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='planning',
            field=models.DateField(),
        ),
    ]
