# Generated by Django 3.1.7 on 2021-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210227_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='planning',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
