# Generated by Django 3.1.7 on 2021-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210227_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='level',
            field=models.CharField(choices=[('-', '-'), ('Easy', 'easy'), ('Hard', 'hard')], max_length=100, null=True),
        ),
    ]
