# Generated by Django 3.1.7 on 2021-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210227_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='level',
            field=models.CharField(choices=[('-', '-'), ('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'Hard')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='risk',
            field=models.CharField(choices=[('-', '-'), ('Not risky', 'not risky'), ('OK', 'OK'), ('Risky', 'risky'), ('Very risky', 'very risky')], max_length=100, null=True),
        ),
    ]
