# Generated by Django 3.1.7 on 2021-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210403_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correctness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimateb_by_calc',
            field=models.CharField(max_length=253, null=True),
        ),
    ]
